version: "3"

services:
  static:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - static:/usr/share/nginx/html/:ro
    depends_on:
      - cms

  cms:
    build: .
    volumes:
      - cms-db:/app/cms/.tmp/
      - static:/app/static/out/
    environment:
      - NEXT_PUBLIC_STRAPI_API_URL=http://cms:1337
    ports:
      - 1337:1337

volumes:
  cms-db: {}
  static: {}
