version: "3"

services:
  static:
    image: nginx
    ports:
      - 80:80
    volumes:
      - static:/usr/share/nginx/html:ro
    depends_on:
      - cms

  cms:
    build: .
    volumes:
      - static:/app/build
      - cms-db:/app/cms/.tmp
      - uploads:/app/cms/public/uploads
    ports:
      - 1337:1337

volumes:
  cms-db: {}
  static: {}
  uploads: {}
